import CloudKit
import Foundation

/// Parses CloudKit remote-notification payloads to identify whether they
/// correspond to one of our quota push zones. Used by the iOS
/// `UNNotificationServiceExtension` to decide whether to enrich the push with
/// provider data — and unit-testable independent of the extension target.
public enum QuotaZoneNotificationParser {

    /// Hard cap for warning-zone reads in the notification service extension.
    /// A saturated legacy zone falls back to its generic alert instead of
    /// paging without limit or guessing which account/window changed.
    public static let warningRecordScanLimit = 500

    public static func warningRecordScanReachedLimit(
        recordsExamined: Int,
        hasContinuationCursor: Bool) -> Bool
    {
        recordsExamined >= Self.warningRecordScanLimit && hasContinuationCursor
    }

    /// Quota states the parser recognizes — must stay in lockstep with the
    /// states `QuotaTransitionSubscriptions` registers and the `state`
    /// strings Mac writes in `QuotaTransition` records.
    public enum QuotaState: String, Sendable, Equatable, CaseIterable {
        case depleted
        case restored
        /// iOS 1.6.0 / Mac 0.25.2 — pre-depletion warning at a
        /// configured threshold (e.g. 50% remaining).
        case warning
    }

    /// Returns `true` if the given zone is one of the quota push zones whose
    /// notifications we want the service extension to enrich.
    ///
    /// Supports both:
    /// - The Build 42–53 legacy global zones (`QuotaDepletedZone`,
    ///   `QuotaRestoredZone`) — kept so users who haven't re-run app launch
    ///   yet still get title rewrites.
    /// - The Build 54+ per-provider zones (`Quota-{providerID}-{state}Zone`)
    ///   generated by `QuotaProviderList.quotaZoneName`.
    public static func isQuotaPushZone(_ zoneID: CKRecordZone.ID) -> Bool {
        let name = zoneID.zoneName
        if name == CloudSyncConstants.quotaDepletedZoneName ||
           name == CloudSyncConstants.quotaRestoredZoneName
        {
            return true
        }
        return self.parseQuotaZoneName(name) != nil
    }

    /// Parses a per-provider zone name `"Quota-{providerID}-{state}Zone"`
    /// into its component providerID + state. Returns `nil` for legacy
    /// global zones or non-quota zones.
    ///
    /// **Format contract**: must match `QuotaProviderList.quotaZoneName(providerID:state:)`
    /// byte-for-byte. Any drift silently breaks NSE enrichment, which
    /// falls back to the static subscription alertBody — no regression
    /// but no title rewrite either.
    public static func parseQuotaZoneName(_ name: String) -> (providerID: String, state: QuotaState)? {
        guard name.hasPrefix("Quota-"), name.hasSuffix("Zone") else { return nil }
        let trimmed = String(name.dropFirst("Quota-".count).dropLast("Zone".count))
        // trimmed should be "{providerID}-{state}" — split on the LAST hyphen
        // so providerIDs containing a hyphen still parse correctly. None do
        // today (all UsageProvider raw values are single-token), but coding
        // defensively here costs nothing.
        guard let dashIndex = trimmed.lastIndex(of: "-") else { return nil }
        let providerID = String(trimmed[..<dashIndex])
        let stateString = String(trimmed[trimmed.index(after: dashIndex)...])
        guard let state = QuotaState(rawValue: stateString) else { return nil }
        guard !providerID.isEmpty else { return nil }
        return (providerID, state)
    }

    /// Parses a warning record's `recordName` into its component window +
    /// threshold. Returns `nil` if the format doesn't match.
    ///
    /// **Format contract**: matches
    /// `CloudSyncManager.writeQuotaWarningTransition`'s recordName
    /// template `"{providerID}[-w{identityHash}[-l{label}]]-{window}-t{threshold}-{hourBucket}"`.
    /// Used by the iOS NSE to format the push body with the specific
    /// window + threshold without needing extra CKRecord fields.
    public static func parseWarningRecordName(
        _ recordName: String
    ) -> (providerID: String, window: String, threshold: Int, windowLabel: String?)? {
        // Split on `-`. Accept legacy names and the optional named-window suffix.
        // providerID itself could theoretically contain a hyphen but doesn't
        // today; assume the simple split is sufficient.
        let parts = recordName.split(separator: "-", omittingEmptySubsequences: false).map(String.init)
        guard parts.count >= 4 else { return nil }
        var contentCount = parts.count
        var windowLabel: String?
        // Read the v0.68 layout for records that may already have been written
        // with identity tokens after the hour bucket.
        if contentCount > 0, parts[contentCount - 1].hasPrefix("l") {
            guard let decoded = self.decodeWindowLabel(String(parts[contentCount - 1].dropFirst())) else {
                return nil
            }
            windowLabel = decoded
            contentCount -= 1
        }
        if contentCount > 0, parts[contentCount - 1].hasPrefix("w") {
            guard self.isWindowIdentityToken(parts[contentCount - 1]) else { return nil }
            contentCount -= 1
        }
        let hourIndex = contentCount - 1
        let thresholdIndex = hourIndex - 1
        let windowIndex = thresholdIndex - 1
        guard hourIndex >= 3, Int(parts[hourIndex]) != nil else { return nil }
        let thresholdPart = parts[thresholdIndex]
        guard thresholdPart.hasPrefix("t"),
              let threshold = Int(thresholdPart.dropFirst())
        else { return nil }
        let window = parts[windowIndex]

        // New writers put identity tokens before the window. This leaves the
        // final `window-tN-hour` shape intact for older iOS notification
        // extensions, which only read the last three components.
        var providerParts = Array(parts[..<windowIndex])
        if providerParts.count >= 2,
           providerParts[providerParts.count - 1].hasPrefix("l"),
           providerParts[providerParts.count - 2].hasPrefix("w")
        {
            guard let decoded = self.decodeWindowLabel(
                String(providerParts[providerParts.count - 1].dropFirst())),
                self.isWindowIdentityToken(providerParts[providerParts.count - 2])
            else { return nil }
            if windowLabel == nil { windowLabel = decoded }
            providerParts.removeLast(2)
        } else if let last = providerParts.last, last.hasPrefix("w") {
            guard self.isWindowIdentityToken(last) else { return nil }
            providerParts.removeLast()
        }
        let providerID = providerParts.joined(separator: "-")
        guard !providerID.isEmpty, !window.isEmpty else { return nil }
        return (providerID, window, threshold, windowLabel)
    }

    /// Creates a warning record name while preserving the suffix read by old
    /// NSE parsers. `identityHash` is a short hash, never a user identity.
    public static func warningRecordName(
        providerID: String,
        window: String,
        threshold: Int,
        hourBucket: Int,
        identityHash: String? = nil,
        windowDisplayLabel: String? = nil) -> String
    {
        var components = [providerID]
        if let identityHash, self.isWindowIdentityToken("w\(identityHash)") {
            components.append("w\(identityHash)")
            if let token = windowDisplayLabel.flatMap(self.encodeWarningWindowLabel) {
                components.append("l\(token)")
            }
        }
        components.append(contentsOf: [window, "t\(threshold)", String(hourBucket)])
        return components.joined(separator: "-")
    }

    private static func isWindowIdentityToken(_ token: String) -> Bool {
        guard token.hasPrefix("w") else { return false }
        let identity = token.dropFirst()
        return identity.count == 24 && identity.allSatisfy(\.isHexDigit)
    }

    /// Encodes a short, non-user-entered display label into a record-name token.
    /// The label is hex encoded so CloudKit's `-` separators remain unambiguous.
    public static func encodeWarningWindowLabel(_ label: String) -> String? {
        let data = Data(label.utf8)
        guard !data.isEmpty, data.count <= 64 else { return nil }
        return data.map { String(format: "%02x", $0) }.joined()
    }

    private static func decodeWindowLabel(_ token: String) -> String? {
        guard !token.isEmpty, token.count.isMultiple(of: 2), token.count <= 128 else { return nil }
        var data = Data()
        var index = token.startIndex
        while index < token.endIndex {
            let end = token.index(index, offsetBy: 2)
            guard let byte = UInt8(token[index..<end], radix: 16) else { return nil }
            data.append(byte)
            index = end
        }
        guard let label = String(data: data, encoding: .utf8), !label.isEmpty else { return nil }
        return label
    }

    /// Zone notifications identify the changed zone but not the triggering
    /// record. Near-simultaneous warning writes must keep a generic body rather
    /// than attaching another record's threshold or period.
    public static func warningRecordsAreAmbiguous(
        transitionTimes: [Date],
        latestTransitionAt: Date? = nil,
        tolerance: TimeInterval = 2) -> Bool
    {
        guard let latest = latestTransitionAt ?? transitionTimes.max() else { return false }
        let contemporaneousCount = transitionTimes.count { time in
            abs(time.timeIntervalSince(latest)) <= tolerance
        }
        return contemporaneousCount > 1
    }

    /// Extracts the quota zone ID from a CloudKit remote-notification user-info
    /// dictionary. Returns `nil` if the payload isn't a `CKRecordZoneNotification`
    /// or the zone isn't one of our quota push zones (defensive against future
    /// zone additions, the legacy `QuotaTransitionsZone`, and non-CloudKit pushes).
    public static func extractQuotaZoneID(
        from userInfo: [AnyHashable: Any]) -> CKRecordZone.ID?
    {
        guard
            let notif = CKNotification(fromRemoteNotificationDictionary: userInfo),
            let zoneNotif = notif as? CKRecordZoneNotification,
            let zoneID = zoneNotif.recordZoneID,
            self.isQuotaPushZone(zoneID)
        else { return nil }
        return zoneID
    }
}
